"""Business logic that keeps PostgreSQL and Elasticsearch in sync."""

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app import search
from app.config import get_settings
from app.models import Document
from app.schemas import DocumentCreate


async def create_document(session: AsyncSession, data: DocumentCreate) -> Document:
    """Persist a document in the DB and add it to the search index.

    The id is generated by the DB; it is then used as the Elasticsearch ``_id``
    so both stores stay in sync. If indexing fails, the DB write is rolled back.
    """
    doc = Document(
        text=data.text,
        rubrics=list(data.rubrics),
        created_date=data.created_date,
    )
    session.add(doc)
    await session.flush()  # assign the generated id without committing yet
    doc_id = doc.id
    try:
        await search.index_document(doc_id, doc.text)
        await session.commit()
    except Exception:
        await session.rollback()
        await search.delete_from_index(doc_id)
        raise
    return doc


async def get_document(session: AsyncSession, doc_id: int) -> Document | None:
    return await session.get(Document, doc_id)


async def search_documents(
    session: AsyncSession, query: str, order: str = "desc"
) -> list[Document]:
    """Full-text search over document text, returned newest-first by default.

    1. Elasticsearch returns candidate ids ranked by relevance.
    2. The DB loads those documents and orders them by ``created_date``,
       returning the first ``search_result_size`` (20).
    """
    settings = get_settings()
    ids = await search.search_ids(query, settings.search_candidate_pool)
    if not ids:
        return []

    created = Document.created_date.asc() if order == "asc" else Document.created_date.desc()
    secondary = Document.id.asc() if order == "asc" else Document.id.desc()
    stmt = (
        select(Document)
        .where(Document.id.in_(ids))
        .order_by(created, secondary)
        .limit(settings.search_result_size)
    )
    result = await session.execute(stmt)
    return list(result.scalars().all())


async def delete_document(session: AsyncSession, doc_id: int) -> bool:
    """Delete a document from the DB and the index.

    Returns True if the document existed in the DB, False otherwise. The index
    entry is removed in both cases to avoid leaving orphans behind.
    """
    doc = await session.get(Document, doc_id)
    if doc is None:
        await search.delete_from_index(doc_id)
        return False
    await session.delete(doc)
    await session.commit()
    await search.delete_from_index(doc_id)
    return True
