"""Load the CSV dataset into PostgreSQL and Elasticsearch.

The source CSV has columns ``text``, ``created_date``, ``rubrics`` and no id;
ids are generated by the database on insert and reused as the Elasticsearch id.

Usage:
    python -m scripts.ingest --csv data/posts.csv
    python -m scripts.ingest --csv data/posts.csv --recreate
"""

import argparse
import ast
import asyncio
import csv
import sys
from datetime import datetime
from pathlib import Path

from elasticsearch.helpers import async_bulk
from sqlalchemy import func, select

from app import search
from app.config import get_settings
from app.db import Base, dispose_engine, get_engine, get_sessionmaker, init_models
from app.models import Document

DATE_FORMAT = "%Y-%m-%d %H:%M:%S"


def parse_rubrics(raw: str | None) -> list[str]:
    """Parse the ``"['VK-1', 'VK-2']"`` python-list-literal into a list."""
    if not raw or not raw.strip():
        return []
    try:
        value = ast.literal_eval(raw)
    except (ValueError, SyntaxError):
        return [raw.strip()]
    if isinstance(value, (list, tuple)):
        return [str(item) for item in value]
    return [str(value)]


def parse_date(raw: str) -> datetime:
    return datetime.strptime(raw.strip(), DATE_FORMAT)


def read_rows(csv_path: Path):
    with csv_path.open(encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            yield row


async def _flush_batch(sessionmaker, index: str, rows: list[dict]) -> int:
    docs = [
        Document(
            text=row["text"],
            rubrics=parse_rubrics(row.get("rubrics")),
            created_date=parse_date(row["created_date"]),
        )
        for row in rows
    ]
    async with sessionmaker() as session:
        session.add_all(docs)
        await session.flush()  # assign ids
        actions = [
            {
                "_index": index,
                "_id": str(doc.id),
                "_source": {"id": doc.id, "text": doc.text},
            }
            for doc in docs
        ]
        await async_bulk(search.get_es(), actions)
        await session.commit()
    return len(docs)


async def ingest(csv_path: Path, batch_size: int = 500, recreate: bool = False) -> int:
    settings = get_settings()

    if recreate:
        # Drop and recreate both stores for a clean reload.
        async with get_engine().begin() as conn:
            await conn.run_sync(Base.metadata.drop_all)
        es = search.get_es()
        await es.indices.delete(index=settings.elasticsearch_index, ignore_unavailable=True)

    await init_models()
    await search.ensure_index()

    sessionmaker = get_sessionmaker()

    # Idempotency guard: don't duplicate data on repeated runs.
    async with sessionmaker() as session:
        existing = await session.scalar(select(func.count()).select_from(Document))
    if existing and not recreate:
        print(
            f"Documents table already has {existing} rows; skipping ingest. "
            f"Use --recreate to reload from scratch."
        )
        return 0

    total = 0
    batch: list[dict] = []
    for row in read_rows(csv_path):
        batch.append(row)
        if len(batch) >= batch_size:
            total += await _flush_batch(sessionmaker, settings.elasticsearch_index, batch)
            batch = []
            print(f"  ... {total} documents loaded", flush=True)
    if batch:
        total += await _flush_batch(sessionmaker, settings.elasticsearch_index, batch)

    await search.refresh_index()
    print(f"Done. Ingested {total} documents into DB and Elasticsearch.")
    return total


async def _main_async(args: argparse.Namespace) -> int:
    csv_path = Path(args.csv)
    if not csv_path.exists():
        print(f"CSV file not found: {csv_path}", file=sys.stderr)
        return 1
    try:
        await ingest(csv_path, batch_size=args.batch_size, recreate=args.recreate)
    finally:
        await search.close_es()
        await dispose_engine()
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description="Ingest the CSV dataset.")
    parser.add_argument("--csv", default="data/posts.csv", help="Path to the CSV file")
    parser.add_argument("--batch-size", type=int, default=500, help="Insert batch size")
    parser.add_argument(
        "--recreate",
        action="store_true",
        help="Drop existing data and reload from scratch",
    )
    args = parser.parse_args()
    raise SystemExit(asyncio.run(_main_async(args)))


if __name__ == "__main__":
    main()
